 
sudo: required
services: 
  - docker

before_install:
  - docker build -t gbozsik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gobzsik/react-test npm test

after_success:
  - docker build -t gbozsik/multi-client ./client
  - docker build -t gbozsik/multi-nginx ./nginx
  - docker build -t gbozsik/multi-server ./server
  - docker build -t gbozsik/multi-worker ./worker